//! Known-safe Windows logs. Scans these three subdirs of `%WINDIR%\Logs\`:
//! `CBS`, `DISM`, `WindowsUpdate`. All are regenerated by Windows on next
//! servicing/update operation.
//!
//! Permission-denied entries are silently skipped by [`crate::scan_util::scan_dir`]
//! — acceptable for scan, NOT for delete (handled at execute time).

use std::path::PathBuf;
use wc_core::{
    Category, CategoryEntry, CategoryId, Environment, Finding, SafetyTier, ScanContext, Version,
};

use crate::scan_util::scan_many;

pub struct WindowsLogsCategory;

impl WindowsLogsCategory {
    pub const ID: CategoryId = "windows.logs";

    fn cache_roots() -> Vec<PathBuf> {
        let logs_root = if let Some(test) = std::env::var_os("WC_TEST_WINDOWS_LOGS_ROOT") {
            PathBuf::from(test)
        } else {
            let windir = std::env::var_os("WINDIR")
                .map(PathBuf::from)
                .unwrap_or_else(|| PathBuf::from(r"C:\Windows"));
            windir.join("Logs")
        };
        vec![
            logs_root.join("CBS"),
            logs_root.join("DISM"),
            logs_root.join("WindowsUpdate"),
        ]
    }
}

impl Category for WindowsLogsCategory {
    fn id(&self) -> CategoryId {
        Self::ID
    }
    fn name(&self) -> &'static str {
        "Windows logs (CBS, DISM, WindowsUpdate)"
    }
    fn safety_tier(&self) -> SafetyTier {
        SafetyTier::Light
    }
    fn version_intro(&self) -> Version {
        Version::V1_0
    }
    fn supports(&self, _env: &Environment) -> bool {
        cfg!(target_os = "windows")
    }
    fn scan(&self, _ctx: &ScanContext) -> Vec<Finding> {
        let roots = Self::cache_roots();
        let refs: Vec<&std::path::Path> = roots.iter().map(|p| p.as_path()).collect();
        scan_many(&refs, Self::ID)
    }
}

inventory::submit! { CategoryEntry { category: &WindowsLogsCategory } }

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn supports_returns_cfg_target() {
        assert_eq!(
            WindowsLogsCategory.supports(&Environment::default()),
            cfg!(target_os = "windows")
        );
    }

    #[test]
    fn scan_honors_test_env_var() {
        let tmp = TempDir::new().expect("tempdir");
        for sub in ["CBS", "DISM", "WindowsUpdate"] {
            fs::create_dir_all(tmp.path().join(sub)).expect("mkdir");
            fs::write(tmp.path().join(sub).join("entry.log"), [0u8; 8]).expect("write");
        }

        std::env::set_var("WC_TEST_WINDOWS_LOGS_ROOT", tmp.path());
        let findings = WindowsLogsCategory.scan(&ScanContext::default());
        std::env::remove_var("WC_TEST_WINDOWS_LOGS_ROOT");

        assert_eq!(findings.len(), 3);
        assert!(findings
            .iter()
            .all(|f| f.category_id == WindowsLogsCategory::ID));
    }
}
